// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkpvbreyafojrgrtexaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcHZicmV5YWZvanJncnRleGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE3MTk2OTEsImV4cCI6MjA5NzI5NTY5MX0.WUpW780Sg0md0ubEXu0KOULjY6_qAl5UC2cnlIt7Ty0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});